# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'BeforAfter' do

  pod 'FLAnimatedImage', '~> 1.0'
  pod 'ionicons'
  pod 'AFNetworking', '~>2.0'
  pod 'SVProgressHUD'
  pod 'SDWebImage'

end

target 'BeforAfterTests' do

end
