# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'BeforAfter' do

  pod 'FLAnimatedImage', '~> 1.0'
  pod 'ionicons'

end

target 'BeforAfterTests' do

end
